name: Run tests

on:
  pull_request:
  push:

jobs:
  run_tests:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install hatch
        run: pip install --upgrade hatch

      - name: Run mypy
        run: hatch run dev:mypy src

      - name: Check styling
        run: hatch run dev:black .

      - name: Run tests
        run: hatch run dev:test
